kubernetes-dashboard:
  fullnameOverride: 'kubernetes-dashboard'

rabbitmq:
  auth:
    username: 'cltl'
    password: 'cltl'
  ingress:
    enabled: true
    hostname: kubernetes.docker.internal
    path: /mq/(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    tls: false