apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-consumer
spec:
  selector:
    matchLabels:
      app: demo-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-consumer
    spec:
      containers:
      - name: demo-consumer
        image: cltl/demo-consumer:0.0.dev1
        volumeMounts:
          - name: cltl-config
            mountPath: /cltl_k8_config
      volumes:
        - name: cltl-config
          configMap:
            name: cltl-config