apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-producer
spec:
  selector:
    matchLabels:
      app: demo-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-producer
    spec:
      containers:
      - name: demo-producer
        image: cltl/demo-producer:0.0.dev1
        volumeMounts:
          - name: cltl-config
            mountPath: /cltl_config
      volumes:
        - name: cltl-config
          configMap:
            name: cltl-config